[package]
name = "escrow-native"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.13"
thiserror = "1.0.64"
spl-token = {version = "6.0.0", features = ["no-entrypoint"]}
arrayref = "0.3.9"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
